### ISSUE TITLE
Crate maintenance status?

### ISSUE THREAD

**Issue by smklein** [overdrivenpotato/bb8-diesel#4]
First of all, thanks for putting this crate out there. Super useful feature, which I'm interested in picking up an using.

**If this crate is being actively supported**, I would love to contribute - especially for updating dependencies to tokio 1.0. However, given that a PR has existed for that for a while...

**Is this crate not being maintained**? If so - that's fine, life goes on, and I may look into forking / supporting my own variant. However, I'd only want to do so if contributing was no longer an option!

**Comment by overdrivenpotato** [comment]
Hi @smklein, I'm not able to actively maintain this repo, but I can set up an auto-publishing CI and give you push access to the repo if you'd like to maintain it. Do you have Discord?

**Comment by smklein** [comment]
Ah, that sounds great! I'm smklein#5627 on Discord if you'd prefer to chat there

**Comment by smklein** [comment]
(Either way, lemme know. I'm currently updating dependencies + adding documentation and examples)
